### ISSUE TITLE
Decide which hipster technology to use for the website

### ISSUE THREAD

**Issue by jnferner** [MyelinAI/website#6]
I heard [vue.js](https://vuejs.org/) is considered good hipster.  
We can also go full hipster and use [phoenix](http://phoenixframework.org/).  
Or, we use go static hipster generator and use [gutenberg](https://www.getgutenberg.io/)?

**Comment by Mafii** [comment]
I would love to work together with @bash if he is fine with me creating the backend in c# and he does the frontend in js. 

What do you think of KO.js?

**Comment by SirRade** [comment]
Never used it, but it looks cool!

**Comment by jnferner** [comment]
@bash Can this be closed? Are you satisfied with your current stack?

**Comment by bash** [comment]
Yup, I think the current stack works ok.
