### ISSUE TITLE
Buy digital ocean droplet

### ISSUE THREAD

**Issue by jnferner** [MyelinAI/website#7]
Questions to answer before purchase:
- [x] Which OS?
    - The newest Fedora Rawhide
- [x] Which tier?
    - The 5$ one, we can still scale if needed
- [x] Should we host it somewhere else than Digital Ocean?
    - No one's against DO
- [x] Which account will own it? Do we create a new Myelin Account?
    - @bash created a team for us

Next steps:
`5$ * 12 Months / 4 People = 15$` have to be transferred by everyone to @bash's bank account so he can buy the server for a year whenever he starts implementing the website.
- [x] @bash 
- [x] @SirRade
- [x] @jeremystucki 
- [x] @Mafii 

After that:
- [x] @bash buys the server whenever he feels like starting to work on the website.

**Comment by bash** [comment]
Digitalocean has Teams: https://www.digitalocean.com/community/tutorials/how-to-use-teams-on-digitalocean

**Comment by SirRade** [comment]
Wow, that's cool! Do I understand it right that this way someone "shares" their account n a limited way with other people? In that case that one account would be something like the "master server manager", right?

**Comment by SirRade** [comment]
Next question would have been who to set up as an owner of the DO team, but I see @bash already took care of that ;)

**Comment by bash** [comment]
My thoughts on tier and OS:
- I recommend starting with the 5$ droplet. We can scale upwards if we need more storage/ram/etc.
- Obviously Fedora 😉

**Comment by SirRade** [comment]
@Mafii @jeremystucki Is Fedora 5$ okay? Stable or Rawhide?

**Comment by jeremystucki** [comment]
Stable is for the weak

**Comment by Mafii** [comment]
5$ per month? Fine for me.

**Comment by SirRade** [comment]
Looks like the tech is settled then. Next step: Payment (Check my first comment)

**Comment by bash** [comment]
Just bought the DO droplet
